"""empty message

Revision ID: 111c50e4cb9
Revises: 4390b8f94c2
Create Date: 2015-04-06 08:12:09.412953

"""

# revision identifiers, used by Alembic.
revision = '111c50e4cb9'
down_revision = '4390b8f94c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
