"""empty message

Revision ID: 166ca3fb488
Revises: None
Create Date: 2015-03-24 23:29:05.068558

"""

# revision identifiers, used by Alembic.
revision = '166ca3fb488'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
