"""empty message

Revision ID: 1cf49f2e065
Revises: 166ca3fb488
Create Date: 2015-03-25 13:05:33.665008

"""

# revision identifiers, used by Alembic.
revision = '1cf49f2e065'
down_revision = '166ca3fb488'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
