"""empty message

Revision ID: 26269ae6aaf
Revises: 58116ab2146
Create Date: 2015-04-06 08:13:50.993105

"""

# revision identifiers, used by Alembic.
revision = '26269ae6aaf'
down_revision = '58116ab2146'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
