"""empty message

Revision ID: 2a7a17762e
Revises: 1cf49f2e065
Create Date: 2015-03-25 13:07:30.484847

"""

# revision identifiers, used by Alembic.
revision = '2a7a17762e'
down_revision = '1cf49f2e065'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
