"""empty message

Revision ID: 337988e24a
Revises: 2a7a17762e
Create Date: 2015-03-25 13:09:04.297704

"""

# revision identifiers, used by Alembic.
revision = '337988e24a'
down_revision = '2a7a17762e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
