"""empty message

Revision ID: 3c498426306
Revises: 55158b0de87
Create Date: 2015-04-06 08:10:15.584517

"""

# revision identifiers, used by Alembic.
revision = '3c498426306'
down_revision = '55158b0de87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
