"""empty message

Revision ID: 3da5dc0f926
Revises: 35ce397b8e1
Create Date: 2015-04-06 01:25:36.035912

"""

# revision identifiers, used by Alembic.
revision = '3da5dc0f926'
down_revision = '35ce397b8e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
