"""empty message

Revision ID: 3e599c53e24
Revises: 337988e24a
Create Date: 2015-03-25 19:45:03.098117

"""

# revision identifiers, used by Alembic.
revision = '3e599c53e24'
down_revision = '337988e24a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
