"""empty message

Revision ID: 4390b8f94c2
Revises: 3c498426306
Create Date: 2015-04-06 08:11:44.327225

"""

# revision identifiers, used by Alembic.
revision = '4390b8f94c2'
down_revision = '3c498426306'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
