"""empty message

Revision ID: 453538bfd4b
Revises: 111c50e4cb9
Create Date: 2015-04-06 08:12:42.471473

"""

# revision identifiers, used by Alembic.
revision = '453538bfd4b'
down_revision = '111c50e4cb9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
