"""empty message

Revision ID: 55158b0de87
Revises: 1c65e9724bd
Create Date: 2015-04-06 08:09:41.869168

"""

# revision identifiers, used by Alembic.
revision = '55158b0de87'
down_revision = '1c65e9724bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
