"""empty message

Revision ID: 58116ab2146
Revises: 453538bfd4b
Create Date: 2015-04-06 08:13:13.336046

"""

# revision identifiers, used by Alembic.
revision = '58116ab2146'
down_revision = '453538bfd4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
